### ISSUE TITLE
Push reports to gh-pages with github run_number 

### ISSUE THREAD

**Issue by shwetankverma** [mgrybyk/allure-report-branch-js-action#8]
I tried latest action version :

      
```
- name: Checkout gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages # branch name
          path: gh-pages-dir # checkout path

      - name: Allure Report Action
        uses: mgrybyk/allure-report-branch-js-action@v1.1.1
        if: always()
        continue-on-error: true
        id: allure # used in comment to PR
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages-dir'
          report_dir: 'allure-raw'

      - name: Git Commit and Push Action
        uses: mgrybyk/git-commit-pull-push-action@v1.2.3
        if: always()
        with:
          repository: gh-pages-dir
          branch: gh-pages
          pull_args: --rebase -X ours
```

Now the thing is, when I used simple-elf/allure-report-action@master and peaceiris/actions-gh-pages@v2, the report was pushed to gh-pages branch into a folder which is   ${{ github.run_number }}-
![image](https://github.com/simple-elf/allure-report-action/assets/11815328/85588c96-ebcf-4ed5-a096-d4be97fd656f)

and I can access the report as report-url/ ${{ github.run_number }}

But through this new approach, the report is being to gh-pages branch into a folder like /allure-js-action/sv-selfhosted/self-test/7752762443_1706860034355
7752762443_1706860034355 is  runUniqueId
Can I achieve to push the report to a folder with ${{ github.run_number }}, so that report can be accessed same way as before?

@mgrybyk
